<h1 style="text-align: center;">Music Recommendation System</h1>

The goal of this project is to build a music recommendation system that suggests similar songs based on audio features.

Import Libraries and Load Dataset

In [14]:
#import libraries
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
#load dataset
df = pd.read_csv("dataset.csv")

In [16]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

EDA - Exploratory Data Analysis

In [17]:
df.shape

(114000, 21)

In [18]:
df.columns

Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

Preprocessing

In [20]:
df = df[[
    "track_name",
    "artists",
    "track_genre",
    "danceability",
    "energy",
    "loudness",
    "tempo",
    "valence"
]]

df.head()

,track_name,artists,track_genre,danceability,energy,loudness,tempo,valence
0,Comedy,Gen Hoshino,acoustic,0.676,0.4610,-6.746,87.917,0.715
1,Ghost - Acoustic,Ben Woodward,acoustic,0.420,0.1660,-17.235,77.489,0.267
2,To Begin Again,Ingrid Michaelson;ZAYN,acoustic,0.438,0.3590,-9.734,76.332,0.120
3,Can't Help Falling In Love,Kina Grannis,acoustic,0.266,0.0596,-18.515,181.740,0.143
4,Hold On,Chord Overstreet,acoustic,0.618,0.4430,-9.681,119.949,0.167

In [21]:
df.isnull().sum()

track_name      1
artists         1
track_genre     0
danceability    0
energy          0
loudness        0
tempo           0
valence         0
dtype: int64

In [22]:
df.dropna(inplace=True)

In [23]:
df.drop_duplicates(subset=["track_name", "artists"], inplace=True)

df.shape

(81343, 8)

Modeling

In [24]:
features = df[[
    "danceability",
    "energy",
    "loudness",
    "tempo",
    "valence"
]]

features.head()

   danceability  energy  loudness    tempo  valence
0         0.676  0.4610    -6.746   87.917    0.715
1         0.420  0.1660   -17.235   77.489    0.267
2         0.438  0.3590    -9.734   76.332    0.120
3         0.266  0.0596   -18.515  181.740    0.143
4         0.618  0.4430    -9.681  119.949    0.167

In [25]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(song):
    index = df[df["track_name"] == song].index[0]

    distances = cosine_similarity(
        [scaled_features[index]],
        scaled_features
    )[0]

    songs_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in songs_list:
        print(df.iloc[i[0]].track_name, "-", df.iloc[i[0]].artists)

In [27]:
recommend("Blinding Lights")

Overwhelm - Alphaxone
Remembering You - Tony O'Connor
Imipramine (Pt.1) - PERMEATE
Autumn (Solo Piano) - Ryan Stewart
Asmr: Big Air Conditioner - ASMR HD

The music recommendation system was successfully built using feature-based similarity techniques.

By analyzing numerical audio features such as danceability, energy, loudness, tempo, and valence, we created a recommendation engine capable of suggesting similar songs.

This project demonstrates how similarity-based approaches can be effectively applied to large-scale music datasets without requiring user interaction data.

Saving

In [28]:
import pickle

pickle.dump(df, open("music_df.pkl", "wb"))
pickle.dump(scaled_features, open("music_features.pkl", "wb"))

In [29]:
import os
os.listdir()

['.config', 'music_df.pkl', 'music_features.pkl', 'dataset.csv', 'sample_data']